import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

type WebFeaturesData = {
  features?: Record<string, unknown>;
};

async function main() {
  console.log("Fetching web-features data...");
  const response = await fetch("https://unpkg.com/web-features/data.json");
  if (!response.ok) {
    throw new Error(`Failed to fetch data: ${response.statusText}`);
  }

  const data = (await response.json()) as WebFeaturesData;
  // The structure contains top level keys like "features", "browsers", etc.
  // We want the keys of the "features" object.
  const ids = Object.keys(data.features || {}).sort();

  console.log(`Found ${ids.length} feature IDs.`);

  const fileContent = `/**
 * This file is auto-generated by scripts/generate-ids.ts
 * Do not edit manually.
 */

export const featureIds = [
${ids.map((id) => `  "${id}",`).join("\n")}
] as const;

export type FeatureId = typeof featureIds[number];
`;

  const outputPath = path.resolve(__dirname, "../src/feature-ids.ts");
  await fs.writeFile(outputPath, fileContent, "utf-8");
  console.log(`Wrote feature IDs to ${outputPath}`);
}

main().catch(console.error);
